Basic profile & fixing of async tests
xi-effect/xi.auth pull request #11
Opened 2023-12-27 18:22 UTC by porebrikk

2023-12-28 14:31 UTC, niqzart reviewed
Не удержался

2023-12-28 14:31 UTC, niqzart commented on app/routes/users_rst.py
> +router = APIRouter(tags=["current user"], prefix="/current")
Нигде такого нет в проекте, и не надо добавлять

2023-12-28 14:31 UTC, niqzart commented on app/routes/users_rst.py
> +    return user
В описании задачи 1 метод

2023-12-28 14:31 UTC, niqzart commented on tests/functional/test_profile.py
> +BASE_LINK: str = "/api/users/current"
Нигде в проекте такого нет и не надо добавлять

2023-12-28 14:31 UTC, niqzart commented on tests/functional/test_profile.py
> +    "test_display_name", [False, True], ids=["no_display_name", "with_display_name"]
В тестах всё тестится и всё тестовое. В других тестах другой префикс в котором есть понятный смысл

2023-12-28 14:31 UTC, niqzart commented on tests/functional/test_profile.py
> +    update_data = {}
Типизация

2023-12-30 15:01 UTC, alina-vorontsova requested changes

2023-12-30 15:08 UTC, porebrikk commented on app/models/users_db.py
> +    username: Mapped[str] = mapped_column(String(100), unique=True, index=True)
@niqzart тут вопрос скорее к тебе, чем ко мне :)

2023-12-31 10:30 UTC, niqzart requested changes

2023-12-31 10:30 UTC, niqzart commented on app/main.py
> +app.include_router(users_rst.router, prefix="/api/users/current")
Тогда файлик стоит назвать соответствующим образом, `current_user_rst`

2023-12-31 10:30 UTC, niqzart commented on app/routes/users_mub.py
> +async def update_user(user_id: int, user_data: User.InputPatchModel) -> User:
Админка должна давать возможность редактировать все поля

2023-12-31 10:30 UTC, niqzart commented on app/routes/users_rst.py
> +    The method implements updating the profile data of an authorized user
Дока не по формату и ни о чём

2023-12-31 10:30 UTC, niqzart commented on app/routes/users_rst.py
> +        raise SignupResponses.USERNAME_IN_USE.value
Очень странные утилиты. В других местах это не делается таким образом

2023-12-31 10:30 UTC, niqzart commented on app/routes/users_rst.py
> +    responses=AuthorizedResponses.responses(),
Не те Responses

2023-12-31 10:30 UTC, niqzart commented on tests/functional/test_profile.py
> +@pytest.mark.parametrize("theme", [False, True], ids=["default_theme", "dark_theme"])
Не существует дефолтной и тёмной темы, поле темы это строка

2023-12-31 10:30 UTC, niqzart commented on tests/functional/test_profile.py
> +@pytest.mark.parametrize("theme", [False, True], ids=["default_theme", "dark_theme"])
Всё ещё названия переменных не отражают их сути. Переменная username, например, по названию должна содержать username, но этого не делает

2023-12-31 10:30 UTC, niqzart commented on tests/functional/test_profile.py
> +    """
Документация не по формату и ни о чём. В тестах её делать не просили

2023-12-31 10:30 UTC, niqzart commented on app/models/users_db.py
> +            (username, Annotated[str, Field(pattern=r"[a-z0-9_\.]{5,100}")]),
Не DRY

2023-12-31 10:30 UTC, niqzart commented on app/models/users_db.py
> +    username: Mapped[str] = mapped_column(String(100), unique=True, index=True)
Не надо это перемещать

2023-12-31 10:30 UTC, niqzart commented on app/models/users_db.py
> +    ProfilePatchModel = ProfileModel.as_patch()
ProfileModel никогда не используется

2023-12-31 10:37 UTC, niqzart commented on app/routes/users_rst.py
> +    The method implements updating the profile data of an authorized user
Если формулируем на русском, это ответ на вопрос "зачем вызывать эндпоинт?", не содержащий вопроса и "чтобы". Т.е. "Метод нужно вызвать, чтобы обновить профиль текущего пользователя" -> "Обновить данные профиля текущего пользователя" -> "Update current user's profile data"

2023-12-31 10:43 UTC, niqzart commented on app/routes/users_rst.py
> +    The method implements updating the profile data of an authorized user
⬆️ применимо для документирования endpoint-ов в openapi-документации, для документирования кода другие правила и вопросы

2023-12-31 10:46 UTC, niqzart commented on app/models/users_db.py
> +    username: Mapped[str] = mapped_column(String(100), unique=True, index=True)
В итоге делаем 30

2023-12-31 11:11 UTC, porebrikk commented on app/routes/users_rst.py
> +        raise SignupResponses.USERNAME_IN_USE.value
Что конкретно странно?

2023-12-31 11:11 UTC, porebrikk commented on tests/functional/test_profile.py
> +@pytest.mark.parametrize("theme", [False, True], ids=["default_theme", "dark_theme"])
У нас по дефолту значение "system" согласно таске

2023-12-31 12:50 UTC, niqzart commented on app/routes/users_rst.py
> +        raise SignupResponses.USERNAME_IN_USE.value
Всё))

2023-12-31 12:50 UTC, niqzart commented on tests/functional/test_profile.py
> +@pytest.mark.parametrize("theme", [False, True], ids=["default_theme", "dark_theme"])
Я знаю

2023-12-31 12:53 UTC, niqzart commented on app/routes/users_rst.py
> +        raise SignupResponses.USERNAME_IN_USE.value
1. Верификация None
2. Это instance-метод, который не использует instance
3. Возвращаемое значение не используется
4. В других местах это не делается таким образом

2024-01-01 07:59 UTC, porebrikk commented on app/routes/users_rst.py
> +        raise SignupResponses.USERNAME_IN_USE.value
2 - С self вытаскивается id юзера, чтобы не передавать дополнительный аргумент в метод.
3 - Это проверка на уникальность юзернейма. Я мог бы наворотить ифов с выдачей булевого значения, но зачем?
1,4 - Не понимаю, что ты имеешь в виду.
5 - asyncpg не ест в качетсве аргументов PatchDefaultType там, где он ожидает str. Это решаемо с помощью str(), но выглядит костыльно.

2024-01-01 12:52 UTC, niqzart commented on app/routes/users_rst.py
> +        raise SignupResponses.USERNAME_IN_USE.value
Это всё решаемые проблемы

2024-01-04 14:48 UTC, alina-vorontsova reviewed
Такое вот ревью! Работаю над тем, чтобы находить более существенные моменты для исправления...

2024-01-04 14:48 UTC, alina-vorontsova commented on tests/functional/test_users.py
> +async def test_getting(
Может, по аналогии с тестами сессии в xi.auth и тестами в xi.backend, в названии теста прописывать объект, над которым совершается действие? То есть, test_getting -> test_user_getting, test_updating -> test_user_updating и так далее.

2024-01-05 18:19 UTC, niqzart commented on app/main.py
> +app.include_router(users_rst.router, prefix="/api/users/current")
Не просто так написал user вместо users. Текущий пользователь-то один

2024-01-05 18:32 UTC, niqzart commented on app/models/users_db.py
> +    username: Mapped[str] = mapped_column(String(30), unique=True, index=True)
Индекс объявлен в теле модели, unique — тоже

2024-01-05 18:32 UTC, niqzart commented on app/models/users_db.py
> +    InputPatchModel = InputModel.extend(columns=[display_name, theme]).as_patch()
Input тут не при делах, она специально была Patch. Может FullPatchModel?

2024-01-05 18:32 UTC, niqzart commented on app/models/users_db.py
> +    FullModel = ProfilePatchModel.extend(columns=[id, email])
Я же писал, что поля Patch-модели останутся patch-полями. Эта модель, например, скажет, что username необязательное свойство user-а, хотя это неправда

2024-01-05 18:32 UTC, niqzart commented on app/utils/users.py
> +    USERNAME_IN_USE = (HTTP_409_CONFLICT, "Username already in use")
retrieve_user никогда не возвращает такой ответ

2024-01-05 18:32 UTC, niqzart commented on app/utils/users.py
> +    USERNAME_IN_USE = (HTTP_409_CONFLICT, "Username already in use")
Выносить эти в отдельный файл не имеет смысла, если они используются только в одном месте

P.S. Если после правок "они используются только в одном месте" станет неправдой — то супер логично их выносить

2024-01-05 18:32 UTC, niqzart commented on app/utils/users.py
> +    USERNAME_IN_USE = (HTTP_409_CONFLICT, "Username already in use")
`.responses()`, кстати, возвращает dict, можно попробовать чего-то с этим натворить

2024-01-05 18:36 UTC, niqzart commented on app/models/users_db.py
> +    FullModel = ProfilePatchModel.extend(columns=[id, email])
А, это где я сказал, что ProfileModel не используется. Стоило мне сказать, что в ней есть смысл из-за этих двух моделей как раз

2024-01-08 22:34 UTC, niqzart approved these changes

2024-01-21 20:25 UTC, merged