feat: extended last_password_change functionality
xi-effect/xi.auth pull request #39
Opened 2024-04-08 12:55 UTC by max31ru12

2024-04-09 15:41 UTC, kinuser requested changes

2024-04-09 15:41 UTC, kinuser commented on app/models/sessions_db.py
> +t = TokenGenerator(randomness=40, length=50)
issue: на проекте используется дескриптивный нейминг

2024-04-09 15:41 UTC, kinuser commented on app/models/sessions_db.py
> +            token = t.generate_token()
question: вроде же обсуждалось сделать это через делегацию?

2024-04-09 15:41 UTC, kinuser commented on app/routes/current_user_rst.py
> +
question: 409 стасус?

suggestion: можно назвать десприктивнее, например `OLD_PASSWORD_IS_SAME`

2024-04-09 15:41 UTC, kinuser commented on app/routes/current_user_rst.py
issue: на предыдущем типе были ограничения по валидации, а сейчас просто строчка. По хорошему надо бы подумать над этим

2024-04-09 16:33 UTC, max31ru12 commented on app/models/sessions_db.py
> +            token = t.generate_token()
Там был пример, как можно сделать. Пример не подошел

2024-04-09 18:22 UTC, niqzart commented on app/routes/current_user_rst.py
Обязательно надо, иначе могут абъюзить эндпоинт слишком длинными паролями

2024-04-09 19:40 UTC, kinuser commented on tests/functional/test_profile.py
> +    old_change_time: datetime.datetime = (await get_db_user(user)).last_password_change
polish: лишняя переменная

2024-04-09 19:40 UTC, kinuser commented on tests/functional/test_password_reset.py
> +    assert last_change == (await get_db_user(user)).last_password_change
issue: `assert_response()` забылся

2024-04-09 20:04 UTC, max31ru12 commented on tests/functional/test_profile.py
> +    old_change_time: datetime.datetime = (await get_db_user(user)).last_password_change
Почему лишняя? Она нужна, чтобы после смены пароля иметь старое значение поля last_password_change, а затем сравнивать уже новое значение со старым. Если можно сделать как-то по-другому, готов обсудить :)

2024-04-09 20:08 UTC, niqzart commented on tests/functional/test_profile.py
> +    old_change_time: datetime.datetime = (await get_db_user(user)).last_password_change
Неймниг в любом случае плохой, это не по-английкси и это дата-время, не время

2024-04-09 20:08 UTC, kinuser approved these changes

2024-04-09 20:10 UTC, niqzart commented on tests/functional/test_profile.py
> +    )
issue: два раза old. Но вообще сообщение надо полностью переработать, ни на что другое в проекте не похоже

2024-04-09 20:31 UTC, kinuser approved these changes

2024-04-09 20:31 UTC, kinuser commented on app/models/users_db.py
> +
polish: длинна токена была другая

2024-04-09 21:39 UTC, niqzart commented on app/models/users_db.py
> +
Я попросил поменять, всё ок

2024-04-09 21:39 UTC, niqzart commented on app/models/users_db.py
> +        self.password = self.generate_hash(password)
suggestion (non-blocking): Можно `if not self.is_password_valid(password): ...` затащить в change_password и использовать его в reset_password в место частичной дубликации

P.S. non-blocking значит, что я не настаиваю

2024-04-09 21:39 UTC, niqzart commented on app/models/users_db.py
> +    PasswordChangeType = Annotated[str, Field(min_length=6, max_length=100)]
polish: не используется в модели, можно вытащить прямо в схему в _rst

2024-04-09 21:39 UTC, niqzart commented on app/routes/current_user_rst.py
> +    )
polish: Responses перенести ближе к функции, которая их использует, можно прямо перед ней. Тоже самое можно сотворить с моделями (сначала модель, затем респонсы)

2024-04-09 21:39 UTC, niqzart commented on app/routes/current_user_rst.py
> +        raise PasswordChangeResponse.MATCH_WITH_OLD_PASSWORD
question: Why без `.value`, везде же с ним? Mypy вроде на это кричал... Или норм?

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_password_reset.py
>  import time
suggestion: `from datetime import datetime`. From-импорты всегда предпочтительнее

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_password_reset.py
> +    assert last_change == (await get_db_user(user)).last_password_change
issue: Порядок в assert-е всегда `actual <op> expected`, иначе ошибки будут некорректные

Например, `x == y` pytest читает как "x должно быть равно y". y — правильное значение, x — под вопросом, правильное ли

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_password_reset.py
> +    last_change: datetime.datetime = (await get_db_user(user)).last_password_change
issue: Все обращения к БД должны быть в сессии

polish: Можно получить user-а один раз в setup-е

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_password_reset.py
issue: Нет проверки, что дата последней смены обновилась после сброса пароля, как в `test_changing_user_password`

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_password_reset.py
> +    )
issue: Это дефолт, его писать не надо

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_profile.py
> +    old_change_time: datetime.datetime = (await get_db_user(user)).last_password_change
issue: это не по-английкси и это дата-время, не время. Плюс тоже самое про БД-сессию. Также применимо к `last_change` (за что они разные-то?)))

suggestion: `last_password_change_before`? Или что-то такое

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_profile.py
issue: User-а можно получить 1 раз

2024-04-09 21:39 UTC, niqzart commented on tests/functional/test_profile.py
> +    )
praise: красиво

2024-04-09 21:39 UTC, niqzart commented on app/routes/current_user_rst.py
> +    )
issue: Название и текст не похожи на другие в проекте, плюс два раза old...

Например, `Email already in use`, описывает **проблему**, а не то, что мы не смогли сделать. Проблема в текущем случае в том, что пароль такой же, какой стоит сейчас. Получим что-то вроде `New password matches the current one` (можно перефразировать). Название response-а это производная от текста, `PASSWORD_MATCHES_CURRENT`, например

2024-04-09 21:42 UTC, max31ru12 commented on app/routes/current_user_rst.py
> +        raise PasswordChangeResponse.MATCH_WITH_OLD_PASSWORD
Mypy не ругается

2024-04-09 21:43 UTC, max31ru12 commented on tests/functional/test_profile.py
> +    )
Спасибо)

2024-04-11 12:52 UTC, max31ru12 commented on app/models/users_db.py
> +        self.password = self.generate_hash(password)
Я думал над этим, но грамотно реализовать не получилось. Придется тогда исключение в функции выкидывать, а, следовательно, нужна дополнительная логика обработки. Если можно это код можно сделать лучше - готов обсудить. Но у меня пока нет идей на этот счет

2024-04-13 17:04 UTC, niqzart commented on app/models/sessions_db.py
> +
issue (repeat): Стало на много хуже

2024-04-13 17:04 UTC, niqzart commented on app/models/users_db.py
> +        self.password = self.generate_hash(password)
Я уже описал решение, как это сделать, не знаю, в чём проблема и при чём тут исключения

2024-04-13 17:10 UTC, niqzart commented on app/routes/current_user_rst.py
> +    WRONG_PASSWORD = (HTTP_401_UNAUTHORIZED, "Wrong password")
issue: Менять местами классы не имеет никакого смысла и только усложняет rebase. PasswordProtectedResponses двигать не надо

2024-04-13 17:10 UTC, niqzart commented on tests/functional/test_password_reset.py
>  import time
repeat, не исправлено везде

2024-04-13 17:17 UTC, niqzart commented on tests/functional/test_password_reset.py
> +        db_user: User = await get_db_user(user)
issue: Неконсистентность. В других местах такое не типизируют (в т.ч. ты сам), должно быть одинаково

2024-04-13 17:17 UTC, niqzart commented on tests/functional/test_password_reset.py
> +        previous_last_password_change: datetime = db_user.last_password_change
note: Это необязательная типизация, она и как понятна, современные инструменты её расспознают без дополнительных подсказок

2024-04-14 14:43 UTC, niqzart commented on app/routes/password_reset_rst.py
> +    token: str | None = password_reset_cryptography.decrypt(reset_data.reset_token)
issue: Неконсистентность, в других местах такая типизация не прописывается

2024-04-14 14:44 UTC, niqzart approved these changes

2024-04-15 19:11 UTC, merged